import type { EventsCopy, Lang } from "./types";

export const EVENTS_COPY = {
  en: {
    eyebrow: "Events",
    title: "Upcoming Events",
    viewEvent: "View Event",
    noEvents: "There are currently no upcoming events planned.",
    slideshowEyebrow: "Past Events",
    slideshowTitle: "See what our events are like",
    slideshowButton: "Browse Past Events",
    slideshowLabel: "Past event photos",
    showPhoto: "Show photo",
    yearlyEyebrow: "Throughout the Year",
    yearlyTitle: "What we regularly plan",
    yearlyBody: "Our events bring people together to celebrate Mongolian culture through traditions, performances, and shared community gatherings.",
    naadamTitle: "Summer Naadam",
    naadamBefore: "Around early to mid-July, we usually organize a community celebration of ",
    naadamLink: "Naadam",
    naadamAfter: ". Families and friends come together to celebrate Mongolian culture, tradition, community, and performance.",
    winterTitle: "Winter & Christmas gatherings",
    winterBody: "During the winter, we organize community parties and occasional Christmas celebrations where families can reconnect, celebrate together, and enjoy activities and performances prepared by members of the community.",
    performancesTitle: "Culture takes preparation",
    performancesBody: "Many of our events include cultural performances that take substantial preparation. Volunteers and performers spend time rehearsing dances, songs, presentations, decorations, and activities so each celebration can represent our culture with care.",
    involvedTitle: "Help make these events possible",
    involvedBody: "Volunteers help with rehearsals, preparation, setup, activities, welcoming guests, and event-day work. Donations help cover venues, food, supplies, cultural materials, and other event costs.",
    volunteerButton: "Volunteer With Us",
    donateButton: "Support Our Events",
    loadingEvents: "Loading upcoming events…",
eventsError: "We couldn’t load upcoming events right now. Please try again later.",

freeRegistration: "Free registration",
registrationFrom: "Registration",
  },
  mn: {
    eyebrow: "Арга хэмжээ",
    title: "Удахгүй болох арга хэмжээ",
    viewEvent: "Арга хэмжээг үзэх",
    noEvents: "Одоогоор удахгүй болох арга хэмжээ төлөвлөгдөөгүй байна.",
    slideshowEyebrow: "Өмнөх арга хэмжээнүүд",
    slideshowTitle: "Манай арга хэмжээнүүдтэй танилцаарай",
    slideshowButton: "Өмнөх арга хэмжээнүүд",
    slideshowLabel: "Өмнөх арга хэмжээний зургууд",
    showPhoto: "Зураг үзүүлэх",
    yearlyEyebrow: "Жилийн турш",
    yearlyTitle: "Бидний тогтмол төлөвлөдөг арга хэмжээнүүд",
    yearlyBody: "Манай арга хэмжээнүүд хүмүүсийг нэгтгэж, Монголын соёл уламжлалыг баяр ёслол, тоглолт болон олон нийтийн уулзалтаар дамжуулан тэмдэглэхэд чиглэдэг.",
    naadamTitle: "Зуны Наадам",
    naadamBefore: "Ихэвчлэн долдугаар сарын эхэн болон дунд үеэр бид олон нийтэд зориулсан ",
    naadamLink: "Наадам",
    naadamAfter: " зохион байгуулдаг. Гэр бүл, найз нөхөд цуглан Монголын соёл, уламжлал, олон нийт болон тоглолтыг хамтдаа тэмдэглэдэг.",
    winterTitle: "Өвлийн болон Зул сарын уулзалтууд",
    winterBody: "Өвлийн улиралд бид олон нийтийн үдэшлэг болон зарим Зул сарын баярын уулзалтуудыг зохион байгуулдаг. Эдгээр нь гэр бүл, олон нийтийн гишүүд дахин уулзаж, хамтдаа баярлан, бэлтгэсэн тоглолт болон үйл ажиллагаанд оролцох боломж болдог.",
    performancesTitle: "Соёлын тоглолт бэлтгэл шаарддаг",
    performancesBody: "Манай олон арга хэмжээнд ихээхэн бэлтгэл шаарддаг соёлын тоглолт, үзүүлбэрүүд багтдаг. Сайн дурынхан болон оролцогчид бүжиг, дуу, үзүүлбэр, чимэглэл болон бусад үйл ажиллагааг урьдчилан давтаж, бэлтгэдэг.",
    involvedTitle: "Арга хэмжээг хамтдаа бүтээх",
    involvedBody: "Сайн дурынхан давтлага, бэлтгэл, тохижилт, үйл ажиллагаа, зочдыг угтах болон арга хэмжээний өдрийн ажилд тусалдаг. Хандив нь байр, хоол хүнс, хэрэгсэл, соёлын материал болон бусад зардлыг дэмждэг.",
    volunteerButton: "Сайн дурын ажилтан болох",
    donateButton: "Арга хэмжээг дэмжих",
    loadingEvents: "Удахгүй болох арга хэмжээнүүдийг ачаалж байна…",
eventsError: "Арга хэмжээнүүдийг одоогоор ачаалж чадсангүй. Та дараа дахин оролдоно уу.",

freeRegistration: "Үнэгүй бүртгэл",
registrationFrom: "Бүртгэл",
  },
} as const satisfies Record<Lang, EventsCopy>;
