/** Editable copy; keep the English and Mongolian keys paired. */
export const adminEventCardCopy = {
  en: {
    noCoverImage: "No cover image",
    published: "Published",
    draft: "Draft",
    edit: "Edit",
    saving: "Saving...",
    unpublish: "Unpublish",
    publish: "Publish",
    date: "Date",
    location: "Location",
    registration: "Registration",
    viewRegistrants: "View registrants →",
    disabled: "Disabled",
    free: "Free",
    open: "Open",
    enCa: "en-CA",
    youDoNotHavePermissionToMake:
      "You do not have permission to make this change.",
    couldNotUpdateTheEvent: "Could not update the event.",
  },
  mn: {
    noCoverImage: "Зураг алга",
    published: "Нийтлэгдсэн",
    draft: "Ноорог",
    edit: "Засах",
    saving: "Хадгалж байна...",
    unpublish: "Нуух",
    publish: "Нийтлэх",
    date: "Огноо",
    location: "Байршил",
    registration: "Бүртгэл",
    viewRegistrants: "Бүртгүүлсэн хүмүүсийг харах →",
    disabled: "Хаалттай",
    free: "Үнэгүй",
    open: "Нээлттэй",
    enCa: "mn-MN",
    youDoNotHavePermissionToMake: "Танд энэ өөрчлөлтийг хийх эрх байхгүй.",
    couldNotUpdateTheEvent: "Арга хэмжээг шинэчилж чадсангүй.",
  },
} as const;
