/** Editable copy; keep the English and Mongolian keys paired. */
export const editEventModalCopy = {
  en: {
    pleaseCompleteAllRequiredFields: "Please complete all required fields.",
    registrationCostMustBeAValidAmount:
      "Registration cost must be a valid amount.",
    eventManagement: "Event Management",
    editEvent: "Edit Event",
    eventInformation: "Event information",
    scheduleLocation: "Schedule & location",
    starts: "Starts",
    ends: "Ends",
    location: "Location",
    registration: "Registration",
    allowRegistrationForThisEvent: "Allow registration for this event",
    registrationCostCad: "Registration cost (CAD)",
    coverImage: "Cover image",
    contact: "Contact",
    contactEmail: "Contact email",
    contactPhone: "Contact phone",
    cancel: "Cancel",
    saving: "Saving...",
    saveChanges: "Save Changes",
  },
  mn: {
    pleaseCompleteAllRequiredFields: "Шаардлагатай талбаруудыг бөглөнө үү.",
    registrationCostMustBeAValidAmount: "Бүртгэлийн үнэ буруу байна.",
    eventManagement: "Арга хэмжээ",
    editEvent: "Арга хэмжээ засах",
    eventInformation: "Үндсэн мэдээлэл",
    scheduleLocation: "Огноо ба байршил",
    starts: "Эхлэх",
    ends: "Дуусах",
    location: "Байршил",
    registration: "Бүртгэл",
    allowRegistrationForThisEvent: "Энэ арга хэмжээнд бүртгэл зөвшөөрөх",
    registrationCostCad: "Бүртгэлийн үнэ (CAD)",
    coverImage: "Нүүр зураг",
    contact: "Холбоо барих",
    contactEmail: "Холбоо барих имэйл",
    contactPhone: "Холбоо барих утас",
    cancel: "Болих",
    saving: "Хадгалж байна...",
    saveChanges: "Өөрчлөлт хадгалах",
  },
} as const;
