/** Editable copy; keep the English and Mongolian keys paired. */
export const eventRegistrantsModalCopy = {
  en: {
    registrants: "Registrants",
    searchByNameOrEmail: "Search by name or email...",
    loadingRegistrations: "Loading registrations...",
    couldNotLoadRegistrations: "Could not load registrations.",
    noRegistrantsFound: "No registrants found.",
    name: "Name",
    email: "Email",
    status: "Status",
    registered: "Registered",
    registered2: "Registered",
    cancelled: "Cancelled",
    previous: "Previous",
    next: "Next",
    enCa: "en-CA",
  },
  mn: {
    registrants: "Бүртгэл",
    searchByNameOrEmail: "Нэр эсвэл имэйл хайх...",
    loadingRegistrations: "Бүртгэлийг ачаалж байна...",
    couldNotLoadRegistrations: "Бүртгэлийг ачаалж чадсангүй.",
    noRegistrantsFound: "Бүртгэл олдсонгүй.",
    name: "Нэр",
    email: "Имэйл",
    status: "Төлөв",
    registered: "Огноо",
    registered2: "Бүртгэгдсэн",
    cancelled: "Цуцлагдсан",
    previous: "Өмнөх",
    next: "Дараах",
    enCa: "mn-MN",
  },
} as const;
